name: Daily USCIS Status Check

on:
  #schedule:
  #  - cron: '0 18,21,5 * * *'
  workflow_dispatch:

jobs:
  uscis-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env from secrets
        run: |
          echo "CASE_NUMBER=${{ secrets.CASE_NUMBER }}" >> .env
          echo "SUBMISSION_DATE=${{ secrets.SUBMISSION_DATE }}" >> .env
          echo "EMPLOYER_NAME=${{ secrets.EMPLOYER_NAME }}" >> .env
          echo "SENDER_EMAIL=${{ secrets.SENDER_EMAIL }}" >> .env
          echo "SENDER_PASSWORD=${{ secrets.SENDER_PASSWORD }}" >> .env
          echo "RECIPIENT_EMAIL=${{ secrets.RECIPIENT_EMAIL }}" >> .env
          echo "NOTIFICATION_METHOD=${{ secrets.NOTIFICATION_METHOD }}" >> .env
          echo "SMTP_SERVER=${{ secrets.SMTP_SERVER }}" >> .env
          echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> .env
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
          echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> .env
          echo "PERM_UPDATE_URL=${{ secrets.PERM_UPDATE_URL }}" >> .env
          echo "SCRAPER_TIMEOUT=${{ secrets.SCRAPER_TIMEOUT }}" >> .env
          echo "SCRAPER_RETRIES=${{ secrets.SCRAPER_RETRIES }}" >> .env
          echo "DEFAULT_PROCESSING_RATE=${{ secrets.DEFAULT_PROCESSING_RATE }}" >> .env
          echo "CONFIDENCE_HIGH=${{ secrets.CONFIDENCE_HIGH }}" >> .env
          echo "CONFIDENCE_MEDIUM=${{ secrets.CONFIDENCE_MEDIUM }}" >> .env
          echo "CONFIDENCE_LOW=${{ secrets.CONFIDENCE_LOW }}" >> .env
          echo "LOG_LEVEL=${{ secrets.LOG_LEVEL }}" >> .env
          echo "LOG_FILE=perm_tracker.log" >> .env
          echo "ENABLE_MOCK_DATA=${{ secrets.ENABLE_MOCK_DATA }}" >> .env
          echo "MOCK_POSITION=${{ secrets.MOCK_POSITION }}" >> .env
          echo "MOCK_TOTAL_APPLICATIONS=${{ secrets.MOCK_TOTAL_APPLICATIONS }}" >> .env
          echo "MOCK_PROCESSING_RATE=${{ secrets.MOCK_PROCESSING_RATE }}" >> .env

      - name: Run USCIS tracker script
        run: python main.py

      - name: Upload tracker log
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: daily-uscis-log
          path: uscis_tracker.log 
